name: Setup Go
description: 'Sets up Go environment with private modules'
inputs:
  stainless-api-key:
    required: true
    description: the value of the STAINLESS_API_KEY secret
runs:
  using: composite
  steps:
    - uses: stainless-api/retrieve-github-access-token@v1
      id: get_token
      with:
        repo: dackerman/demostore-go
        stainless-api-key: ${{ inputs.stainless-api-key }}

    - name: Configure Git for private Go modules
      shell: bash
      run: git config --global url."https://x-access-token:${{ steps.get_token.outputs.github_access_token }}@github.com/".insteadOf "https://github.com/"

    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod

    - name: Bootstrap
      shell: bash
      run: ./scripts/bootstrap