#!/bin/bash
set -e

go mod tidy

go build -o terraform-provider-stlstore

pushd scripts
terraform providers schema -json | jq > ../upgrading/after.json
popd

cat ./upgrading/after.json

go run main.go -upgrade