#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" ]]; then
  LOCAL_GO="$1"
  shift
else
  LOCAL_GO=../stainless store-go
fi

echo "==> Linking with local directory"
go mod tidy -e
go mod edit -replace github.com/stainless-sdks/dackerman-store-go="$LOCAL_GO"
