#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" ]]; then
  LOCAL_GO="$1"
  shift
else
  LOCAL_GO=../stainless store-go
fi

echo "==> Linking with local directory"
go mod tidy -e
go mod edit -replace dackerman/demostore-go/v2="$LOCAL_GO"
