name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next

env:
  GOPRIVATE: github.com/dackerman/demostore-go

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Run lints
        run: ./scripts/lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Run tests
        run: ./scripts/test