name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next

env:
  GOPRIVATE: github.com/dackerman/demostore-go

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Run lints
        run: ./scripts/lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Run tests
        run: ./scripts/test
  
  check_breaking_changes:
    name: check_migrate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Build
        run: ./scripts/build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
          terraform_wrapper: false

      - name: Check For Breaking changes
        if: github.event_name == 'pull_request'
        id: breaking_changes
        run: |
          OUTPUT_FILE="changes.json"
          ./scripts/detect-breaking-changes || BREAKING_DETECTED=$?
          if [ -n "$BREAKING_DETECTED" ]; then
            echo "BREAKING_CHANGES_DETECTED=true" >> $GITHUB_OUTPUT
          else
            echo "BREAKING_CHANGES_DETECTED=false" >> $GITHUB_OUTPUT
          fi
          cat $OUTPUT_FILE
          echo "BREAKING_CHANGES_JSON=\"$(cat $OUTPUT_FILE | jq -c)\"" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: ./scripts/post-breaking-changes-comment.js
        env:
          BREAKING_CHANGES_DETECTED: ${{ steps.breaking_changes.outputs.BREAKING_CHANGES_DETECTED }}
          BREAKING_CHANGES_JSON: ${{ steps.breaking_changes.outputs.BREAKING_CHANGES_JSON || '{}' }}