name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next

env:
  GOPRIVATE: github.com/stainless-sdks/dackerman-store-go

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stainless-api/retrieve-github-access-token@v1
        id: get_token
        with:
          repo: stainless-sdks/dackerman-store-go
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Configure Git for private Go modules
        run: git config --global url."https://x-access-token:${{ steps.get_token.outputs.github_access_token }}@github.com/".insteadOf "https://github.com/"

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Bootstrap
        run: ./scripts/bootstrap

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run lints
        run: ./scripts/lint

  test:
    name: test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: ./scripts/test
